# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.PositiveIntegerField(unique=True)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
