# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20171202_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
