# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0005_auto_20171202_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medicos.Medico'),
        ),
    ]
