# Generated by Django 2.0 on 2018-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_estudio_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='posologia',
            field=models.PositiveIntegerField(),
        ),
    ]
