# Generated by Django 2.0.2 on 2018-02-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20180113_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='estado',
        ),
    ]
