# Generated by Django 2.0.2 on 2018-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_remove_estudio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='fecha_completado',
            field=models.DateField(null=True),
        ),
    ]
