# Generated by Django 2.0.2 on 2018-02-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_auto_20180218_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='fecha_completado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
