# Generated by Django 2.0.2 on 2018-03-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_paciente_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='dni',
            new_name='documento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
    ]
