# Generated by Django 2.0.2 on 2018-04-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_auto_20180331_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documento',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
