# Generated by Django 2.0 on 2017-12-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name_plural': 'administradores'},
        ),
    ]
